### ISSUE TITLE
关于适用场景

### ISSUE THREAD

**Issue by rockit-ba** [monoio-rs/monoio#16]
贵项目文档中说明：“如果负载并非常不均衡，相比公平调度模型的Tokio它可能会性能变差”，按照我的理解，多路复用能够在单核实现最好的性能，如果要利用现代机器多核，最好是每个核上使用这种模式，理论上这种模式性能很高。这里负载不均衡的场景是指什么呢？

**Comment by songzhi** [comment]
这里说的是Rust协程调度模型，Tokio的多线程调度器会根据各线程负载情况把Rust协程调度到不同线程，就像操作系统调度线程一样。这种模型的问题就是要求所有协程都必须满足跨线程调度的要求，比如tokio的spawn函数的签名是这样的：
```Rust
pub fn spawn<T>(future: T) -> JoinHandle<T::Output>
where
    T: Future + Send + 'static,
    T::Output: Send + 'static, 
```
它要求future必须满足`Send + 'static`。

而一旦可以跨线程调度，则肯定会发生在同一线程创建的多个协程“真并发”（并行）执行的情况，这又要求所有协程和其共享的数据都是线程安全的。在Rust里面这意味着`Arc` + `Mutex`/`RwLock`或者消息队列。这会引入不小的开销和一定的心智负担。而单线程调度的情况下，只需要使用`Rc<RefCell<T>>`把共享数据包起来就行。

tokio同样支持[单线程调度](https://docs.rs/tokio/1.14.0/tokio/task/struct.LocalSet.html)，且tokio-uring使用的也是单线程的调度器。

**Comment by dyxushuai** [comment]
首先感谢关注我们的项目🥰

考虑的原因有几点：
1. 我们的目标是完全不需要同步原语的（core 之间原子同步的问题，大核情况下性能不理想）
2. io_uring based （异步 IO）的接口和 epoll based （同步无阻塞 IO）接口无法兼容
3. tokio-uring 还是依赖了 epoll 来轮训 io_uring FD 并不是必须的, 并且它使用的是 current thread runtime 并非 LocalSet（需要同步原语，问题同 1）
4. tokio-uring 目前主要支持 file IO，还不支持 net IO。我们的需求场景主要在 net IO
5. 同时我们有需要在多个 thread 之间通过 channel 同步数据（tokio 的 LocalSet 无法满足）

**Comment by dyxushuai** [comment]
> 贵项目文档中说明：“如果负载并非常不均衡，相比公平调度模型的Tokio它可能会性能变差”，按照我的理解，多路复用能够在单核实现最好的性能，如果要利用现代机器多核，最好是每个核上使用这种模式，理论上这种模式性能很高。这里负载不均衡的场景是指什么呢？

我们希望使用的场景是简单或者完全可控：
- 一些符合的场景： proxy（简单，只需要散列一下就能基本均衡），database（可控，把 thread per core 作为首选的存储如：redis）
- 不太适合的：框架（需要提供给业务使用，业务场景复杂多变），sdk（同理）

**Comment by rockit-ba** [comment]
嗯，理解了，我能想到的不均衡也就是业务上的特殊要求会导致。谢谢🙏





------------------ 原始邮件 ------------------
发件人: John Smith ***@***.***&gt;
发送时间: 2021年12月10日 11:38
收件人: bytedance/monoio ***@***.***&gt;
抄送: 今天の吉祥君 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [bytedance/monoio] 关于适用场景 (Issue #16)





  
贵项目文档中说明：“如果负载并非常不均衡，相比公平调度模型的Tokio它可能会性能变差”，按照我的理解，多路复用能够在单核实现最好的性能，如果要利用现代机器多核，最好是每个核上使用这种模式，理论上这种模式性能很高。这里负载不均衡的场景是指什么呢？
  
我们希望使用的场景是简单或者完全可控：
  
一些符合的场景： proxy（简单，只需要散列一下就能基本均衡），database（可控，把 thread per core 作为首选的存储如：redis） 

不太适合的：框架（需要提供给业务使用，业务场景复杂多变），sdk（同理） 
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by songzhi** [comment]
@dyxushuai  目前来看`tokio-uring`的进展缓慢，好久都没人推进了。希望monoio可以尽可能与Rust（异步）生态兼容/一致。比如`AsyncReadRent`的`readv`方法，命名最好和`std::io::Read::read_vectored`一致。

**Comment by NaturelLee** [comment]
既然选择了开源了，私以为应该首先使用English：issues & images & docs。中文版本可以使用xxx_zh.md。

**Comment by PureWhiteWu** [comment]
> 既然选择了开源了，私以为应该首先使用English：issues & images & docs。中文版本可以使用xxx_zh.md。

你好，我们的默认 README、commit message 以及代码注释均为英语。

**Comment by pymongo** [comment]
Please ask question on discussion, I think issue pannel is not the place to ask question
