### ISSUE TITLE
cargo test failed

### ISSUE THREAD

**Issue by SSebo** [monoio-rs/monoio#17]
**Version**
0.0.3

`cargo tree | grep monoio`

`monoio v0.0.3 (/home/sebo/Source/github/monoio/monoio)
├── monoio-macros v0.0.2 (proc-macro) (/home/sebo/Source/github/monoio/monoio-macros)
monoio-compat v0.0.4 (/home/sebo/Source/github/monoio/monoio-compat)
├── monoio v0.0.3 (/home/sebo/Source/github/monoio/monoio) (*)
└── monoio v0.0.3 (/home/sebo/Source/github/monoio/monoio) (*)
monoio-examples v0.0.0 (/home/sebo/Source/github/monoio/examples)
├── monoio v0.0.3 (/home/sebo/Source/github/monoio/monoio) (*)
├── monoio-compat v0.0.4 (/home/sebo/Source/github/monoio/monoio-compat) (*)
`

**Platform**
The output of `uname -a` and `ulimit -l`.
`➜  monoio git:(master) uname -a                                                                    [10/12/21 | 1:03:18]
Linux sebo-nuc10i7fnh 5.10.79-1-MANJARO #1 SMP PREEMPT Fri Nov 12 20:26:09 UTC 2021 x86_64 GNU/Linux
➜  monoio git:(master) ulimit -l                                                                   [10/12/21 | 1:03:20]
64`

**Description**
cargo test failed

`running 1 test
test tcp::tests::test_rw ... FAILED

failures:

---- tcp::tests::test_rw stdout ----
thread 'tcp::tests::test_rw' panicked at 'Failed building the Runtime: Os { code: 12, kind: OutOfMemory, message: "Cannot allocate memory" }', monoio-compat/src/tcp.rs:143:38
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

failures:
    tcp::tests::test_rw

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s`

**Comment by ihciah** [comment]
You can check the memlock settings: https://github.com/bytedance/monoio/blob/master/docs/en/memlock.md

**Comment by SSebo** [comment]
@ihciah It works, thanks ! BTW, Should we notice  `memlock.md`  somewhere like README?
