### ISSUE TITLE
will support AsyncBufReadExt api?

### ISSUE THREAD

**Issue by neetdai** [monoio-rs/monoio#179]
会加入像tokio的[AsyncBufReadExt](https://docs.rs/tokio/1.28.2/tokio/io/trait.AsyncBufReadExt.html) api吗?
will support api like tokio [AsyncBufReadExt](https://docs.rs/tokio/1.28.2/tokio/io/trait.AsyncBufReadExt.html) ?

**Comment by ihciah** [comment]
看起来可以。。~有兴趣PR嘛？:)~
看到PR了
