### ISSUE TITLE
How to get metadata of a file by monoio?

### ISSUE THREAD

**Issue by SuanCaiYv** [monoio-rs/monoio#182]
like Tokio or std, the metadata of a file can be read by metadata() defined in File. But I can't find a method like that in monoio, how should I do?

**Comment by ihciah** [comment]
`statx` op is supported by io_uring but it is not intergrated into monoio. It indeed suffers when read the whole file content.
As a workaround, you can use std's metadata.

**Comment by SuanCaiYv** [comment]
> `statx` op is supported by io_uring but it is not intergrated into monoio. It indeed suffers when read the whole file content.
> As a workaround, you can use std's metadata.

all right, thanks!

**Comment by iamazy** [comment]
@ihciah Any plan to support this feature? it's really useful

**Comment by Zk2u** [comment]
(Commenting to resurface) Also would be useful for our use case.
