### ISSUE TITLE
sorry

### ISSUE THREAD

**Issue by ghost** [monoio-rs/monoio#199]
a

**Comment by zzwxh** [comment]
ioring与liburing几乎一致
libuv或者mio使用的不稳定内部api让我感到恐惧
如果微软把这些当bug修了怎么办
整个windows rust异步生态瞬间倒塌

**Comment by PureWhiteWu** [comment]
不仅是 Rust 异步生态了，所有语言所有异步生态都得挂，包括 C/C++、Go、Java 的。。。。

**Comment by zzwxh** [comment]
你是说微软永远不会更改这一部分以保证兼容性？
使用内部或者不稳定的api是对其他开发者的绑架，除非微软把它们的文档完善起来

**Comment by ihciah** [comment]
目前这块还在实现中，当前主要是 @CarrotzRule123 开发，请问对这块有什么看法吗？
我个人对 windows api 不是很了解，但个人觉得如果大量同类组件都在依赖，那么我们依赖也是没太大问题的。如果能做到像 linux 上探测和切换那应该是最佳方案。

**Comment by zzwxh** [comment]
https://github.com/tokio-rs/mio/issues/1444#issue-792821757
This is the poster example of why you should not use undocumented APIs: it makes your code more fragile, harder to understand, harder to contribute to, and borderline impossible to debug for downstream users. I will never get these twenty hours of my life back. Don't do this! And if you for some reason have to do it, wrap it in hazard tape and provide a slow but obviously correct fallback
这是为什么您不应该使用未记录的 api 的海报示例：它使您的代码更加脆弱，更难以理解，更难以贡献，并且几乎无法为下游用户调试。 我这二十个小时的人生再也回不来了。 不要这样做！ 如果您出于某种原因必须这样做，请将其包裹在危险胶带中并提供缓慢但明显正确的后备措施

你们对此如何回应？

**Comment by JinWeiTan** [comment]
I believe ioringapi is only supported on Windows 11, we would still need to add a fallback for older Windows versions. I doubt Microsoft would fix this bug and willingly break compatibility for Nodejs, Tokio etc. Nevertheless, we can and should implement a ioringapi driver in the future.
