### ISSUE TITLE
How to know a JoinHandle has finished?

### ISSUE THREAD

**Issue by iamazy** [monoio-rs/monoio#202]
**Is your feature request related to a problem? Please describe.**
I hope the server can shutdown gracefully. It's need to know status of all tasks.

**Describe the solution you'd like**
provide `is_finished` method just like tokio's JoinHandle

https://github.com/tokio-rs/tokio/blob/82bef00db452a91382e6f122ac99726cda79a5bc/tokio/src/runtime/task/join.rs#L240-L243

**Comment by ihciah** [comment]
Normally you can await on it. `is_finished` will be supported soon.
