### ISSUE TITLE
cloudwego

### ISSUE THREAD

**Issue by phanirithvij** [monoio-rs/monoio#205]
The README says this is a subproject of cloudwego, so wouldn't it be better if monoio belonged in that organization https://github.com/cloudwego instead?

Edit: There is also https://github.com/monoio-rs, is this fragmentation the correct approach?

**Comment by ihciah** [comment]
We do not do repository migrations for historical reasons. Monoio-rs is used to store related ecological components to not bring too many non-mian repos into bytedance or cloudwego org.

**Comment by phanirithvij** [comment]
Why not try a monorepo for monoio-rs repos then?

And it is possible to get @Monoio namespace as well if needed as per github name squatting policy they will give it to you.
