### ISSUE TITLE
using NUM_CPUS in #[monoio::main(threads = 6, timer_enabled = true)] const NUM_CPUS: usize = std::thread::available_parallelism().unwrap().get();

### ISSUE THREAD

**Issue by ouvaa** [monoio-rs/monoio#252]
using NUM_CPUS in #[monoio::main(threads = 6, timer_enabled = true)] 

const NUM_CPUS: usize = std::thread::available_parallelism().unwrap().get();

how can i do #[monoio::main(threads = NUM_CPUS, timer_enabled = true)] 
?

**Comment by ihciah** [comment]
Setting `threads = 0` will work like this way.
For more complicated need, you can start threads by your own. Currently there's no full-featured threads manager.

**Comment by ouvaa** [comment]
thx
