### ISSUE TITLE
A new trait for Socket

### ISSUE THREAD

**Issue by Lzzzzzt** [monoio-rs/monoio#291]
**Is your feature request related to a problem? Please describe.**
I am trying to implement `AsyncWriteRent` for `File`, but the signature `shutdown` defined in this trait is used to [shutdown]( https://linux.die.net/man/2/shutdown) a socket connection, which is needless for File.

**Describe the solution you'd like**
IMO, there could be something like `SocketShutdown`.

**Describe alternatives you've considered**
It can also do nothing in the implement of `File` and using docs to tell user about why, but a little bit wired.

**Comment by Lzzzzzt** [comment]
@Xuanwo @ihciah any idea?

**Comment by ihciah** [comment]
I think it can be aligned with tokio. In tokio's file impl it impl poll_shutdown as poll_flush.
