### ISSUE TITLE
monoio need support pollable IO driver for cross platform development

### ISSUE THREAD

**Issue by dyxushuai** [monoio-rs/monoio#4]
# Why?
The platform support: https://github.com/bytedance/monoio/blob/master/docs/en/platform-support.md

# How?
We can just use [`mio`](https://github.com/tokio-rs/mio) as our dependency for the pollable IO driver

**Comment by dyxushuai** [comment]
BTW, our arm is simply for facilitate cross-platform development at this time.

**Comment by dyxushuai** [comment]
Compile flag or by target arch is preferred.

**Comment by ethe** [comment]
Another IO library here: https://docs.rs/polling/latest/polling/, compare with mio, maybe it is more convenient for embedding.

**Comment by ihciah** [comment]
> Another IO library here: https://docs.rs/polling/latest/polling/, compare with mio, maybe it is more convenient for embedding.

It enables `EPOLLONESHOT` by default, maybe not efficient enough? We'll review its code later.

**Comment by ethe** [comment]
> > Another IO library here: https://docs.rs/polling/latest/polling/, compare with mio, maybe it is more convenient for embedding.
> 
> It enables `EPOLLONESHOT` by default, maybe not efficient enough? We'll review its code later.

yes mio only supports edge trigger and polling only suports oneshot, they have different limitations.

**Comment by SSebo** [comment]
> BTW, our arm is simply for facilitate cross-platform development at this time.

Does that mean single thread is ok? Otherwise spawn may need `Send`?

**Comment by dyxushuai** [comment]
@SSebo Introduce `mio` is just for cross-platform, and thread-per-core is our design goal. So needn't `Send`.

**Comment by ihciah** [comment]
The #73 solved this issue.
