### ISSUE TITLE
AsyncWriteRent and AsyncReadRent trait who's method maybe need receive the mut self reference

### ISSUE THREAD

**Issue by dyxushuai** [monoio-rs/monoio#9]
I think the IO things can't be read or write concurrently. If we want do that then we can add `Half` APIs. Like what we see in the AsyncRead/AsyncWrite in futures or tokio.

**Comment by dyxushuai** [comment]
Also we can't separate concurrent reads and writes in the runtime context.

**Comment by ihciah** [comment]
If we can keep it memory safe, why we need to get a mut borrow? Concurrent read or write in uring is okay for kernel, then it can be considered as a user behavior.

**Comment by ihciah** [comment]
Close as we have already made it.
For a single TcpStream, do read and write(even multiple read and write) at the same time is safe with io_uring. But as a generic trait, the structs that implement it may have state, and the state need `&mut`.
